---
title: "AirBnB analysis"
author: "MK842 Team 2"
date: "1/12/2018"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r setup2, message=FALSE, echo=FALSE}
library(bit64)
library(data.table)
library(ggplot2)
library(scales)
library(stringr)
library(readr)
library(randomForest)
theme_set(theme_bw())

if (0) {
  print("Creating training and test data sets from a 50/50 split of the CSV")
  air <- read.csv("listings.csv", stringsAsFactors = TRUE)

  airt <- data.table(air)

  airt$price <- parse_number(airt$price)
  airt$extra_people <- parse_number(airt$extra_people)
  airt$cleaning_fee <- parse_number(airt$cleaning_fee)
  airt$security_deposit <- parse_number(airt$security_deposit)
  airt$host_response_rate <- as.integer(sub("%", "", airt$host_response_rate))

  airt[,host_since:=as.numeric(as.Date(host_since))]
  airt[,first_review:=as.numeric(as.Date(first_review))]
  airt[,last_review:=as.numeric(as.Date(last_review))]

  airt[,host_since:=na.roughfix(host_since)]
  airt[,host_response_time:=na.roughfix(host_response_time)]
  airt[,host_response_rate:=na.roughfix(host_response_rate)]
  airt[,host_is_superhost:=na.roughfix(host_is_superhost)]
  airt[,host_listings_count:=na.roughfix(host_listings_count)]
  airt[,host_total_listings_count:=na.roughfix(host_total_listings_count)]
  airt[,host_verifications:=na.roughfix(host_verifications)]
  airt[,host_has_profile_pic:=na.roughfix(host_has_profile_pic)]
  airt[,host_identity_verified:=na.roughfix(host_identity_verified)]
  airt[,neighbourhood_cleansed:=na.roughfix(neighbourhood_cleansed)]
  airt[,zipcode:=na.roughfix(zipcode)]
  airt[,latitude:=na.roughfix(latitude)]
  airt[,longitude:=na.roughfix(longitude)]
  airt[,is_location_exact:=na.roughfix(is_location_exact)]
  airt[,property_type:=na.roughfix(property_type)]
  airt[,room_type:=na.roughfix(room_type)]
  airt[,accommodates:=na.roughfix(accommodates)]
  airt[,bathrooms:=na.roughfix(bathrooms)]
  airt[,bedrooms:=na.roughfix(bedrooms)]
  airt[,beds:=na.roughfix(beds)]
  airt[,bed_type:=na.roughfix(bed_type)]
  airt[,amenities:=na.roughfix(amenities)]
  airt[,square_feet:=na.roughfix(square_feet)]
  airt[,security_deposit:=na.roughfix(security_deposit)]
  airt[,cleaning_fee:=na.roughfix(cleaning_fee)]
  airt[,guests_included:=na.roughfix(guests_included)]
  airt[,extra_people:=na.roughfix(extra_people)]
  airt[,minimum_nights:=na.roughfix(minimum_nights)]
  airt[,maximum_nights:=na.roughfix(maximum_nights)]
  airt[,availability_30:=na.roughfix(availability_30)]
  airt[,availability_60:=na.roughfix(availability_60)]
  airt[,availability_90:=na.roughfix(availability_90)]
  airt[,availability_365:=na.roughfix(availability_365)]
  airt[,number_of_reviews:=na.roughfix(number_of_reviews)]
  airt[,first_review:=na.roughfix(first_review)]
  airt[,last_review:=na.roughfix(last_review)]
  airt[,review_scores_rating:=na.roughfix(review_scores_rating)]
  airt[,review_scores_accuracy:=na.roughfix(review_scores_accuracy)]
  airt[,review_scores_cleanliness:=na.roughfix(review_scores_cleanliness)]
  airt[,review_scores_checkin:=na.roughfix(review_scores_checkin)]
  airt[,review_scores_communication:=na.roughfix(review_scores_communication)]
  airt[,review_scores_location:=na.roughfix(review_scores_location)]
  airt[,review_scores_value:=na.roughfix(review_scores_value)]
  airt[,instant_bookable:=na.roughfix(instant_bookable)]
  airt[,is_business_travel_ready:=na.roughfix(is_business_travel_ready)]
  airt[,cancellation_policy:=na.roughfix(cancellation_policy)]
  airt[,require_guest_profile_picture:=na.roughfix(require_guest_profile_picture)]
  airt[,require_guest_phone_verification:=na.roughfix(require_guest_phone_verification)]
  airt[,calculated_host_listings_count:=na.roughfix(calculated_host_listings_count)]
  airt[,reviews_per_month:=na.roughfix(reviews_per_month)]

  atrain.sampled <- sample(nrow(airt), nrow(airt)/2)
  atrain <- airt[atrain.sampled]
  atest <- airt[!atrain.sampled]
  if (!setequal(union(atest$id, atrain$id), airt$id)) {
    stop("ERROR: The test and training datasets don't add up to the original dataset")
  }

  print("Saving training and test data sets")
  save(atest, file="atest.dat")
  save(atrain, file="atrain.dat")
} else {
  load(file="atrain.dat")
  load(file="atest.dat")
  if (length(intersect(atest$id, atrain$id)) > 0) {
    stop("ERROR: The test and training datasets overlap")
  }
}
```

## Define the formula
```{r formula, echo=TRUE}

air_columns <- c("host_since", "host_response_time", "host_response_rate", "host_is_superhost", "host_listings_count", "host_total_listings_count", "host_verifications", "host_has_profile_pic", "host_identity_verified", "neighbourhood_cleansed", "zipcode", "latitude", "longitude", "is_location_exact", "property_type", "room_type", "accommodates", "bathrooms", "bedrooms", "beds", "bed_type", "square_feet", "security_deposit", "cleaning_fee", "guests_included", "extra_people", "minimum_nights", "maximum_nights", "availability_30", "availability_60", "availability_90", "availability_365", "number_of_reviews", "first_review", "last_review", "review_scores_rating", "review_scores_accuracy", "review_scores_cleanliness", "review_scores_checkin", "review_scores_communication", "review_scores_location", "review_scores_value", "instant_bookable", "is_business_travel_ready", "cancellation_policy", "require_guest_profile_picture", "require_guest_phone_verification", "calculated_host_listings_count", "reviews_per_month")

air_formula <- as.formula(paste0("price ~ ", paste(air_columns, sep=" ", collapse="+")))
```

## Build matrices for train and test

Generate a training matrix and a test matrix from the training and test datasets, dropping the first column (`price`).

```{r build_matrices, echo=TRUE}
air.train_input <- model.matrix(air_formula, atrain)[, -1]
air.train_output <- atrain$price

air.test_input <- model.matrix(air_formula, atest)[, -1]
air.test_output <- atest$price
rsq.frommean <- mean((air.test_output-mean(air.test_output))^2)

```

## Linear regression
```{r}
#fit model
fit.lm <- lm(air_formula, atrain)

yhat.test.lm <- predict(fit.lm)
rsq.test.lm <- mean((air.test_output - yhat.test.lm)^2)

print(sprintf("Linear Regression: rsq %.2f and the prediction from the mean is %.2f", rsq.test.lm, rsq.frommean))
```

## Ridge regression

```{r}
library(glmnet)
fit.ridge <- cv.glmnet(air.train_input, air.train_output, alpha = 0, nfolds = 10)
#set alpha = 0 invoke ridge regression

yhat.test.ridge <- predict(fit.ridge, air.test_input, s = fit.ridge$lambda.min)
rsq.test.ridge <- mean((air.test_output - yhat.test.ridge)^2)

print(sprintf("Ridge Regression: rsq %.2f and the prediction from the mean is %.2f", rsq.test.ridge, rsq.frommean))
```

## Lasso regression

```{r}
fit.lasso <- cv.glmnet(air.train_input, air.train_output, alpha = 1, nfolds = 10)
#set alpha = 1 invoke lasso

yhat.test.lasso <- predict(fit.lasso, air.test_input, s = fit.lasso$lambda.min)
rsq.test.lasso <- mean((air.test_output - yhat.test.lasso)^2)

print(sprintf("Lasso: rsq %.2f and the prediction from the mean is %.2f", rsq.test.lasso, rsq.frommean))

# save Lasso coefficients
lasso.sds <- apply(air.train_input, 2, sd)
lasso.coefs <- as.matrix(coef(fit.lasso, s = "lambda.min"))
lasso.std_coefs <- lasso.coefs[-1, 1] * lasso.sds
write.csv(as.data.frame(lasso.std_coefs),file="lasso_std_coefficients.csv")
write.csv(as.data.frame(lasso.coefs),file="lasso_coefficients.csv")

```

## Elastic net

```{r}
fit.elastic <- cv.glmnet(air.train_input, air.train_output, alpha = 0.5, nfolds = 10)
#picking 0 < alpha < 1, for example set alpha = 0.5 to weigh lasso and ridge penalties equally

yhat.test.elastic <- predict(fit.elastic, air.test_input, s = fit.elastic$lambda.min)
rsq.test.elastic <- mean((air.test_output - yhat.test.elastic)^2)

print(sprintf("Elastic Net: rsq %.2f and the prediction from the mean is %.2f", rsq.test.elastic, rsq.frommean))
```


## Random Forest

Run Random Forest algorithm over the training dataset.

```{r prep_matrices, echo=TRUE}
if (0) {
  fit.rndfor <- randomForest( air.train_input, air.train_output, do.trace = 0,
                            importance = TRUE,
                            keep.forest = TRUE,
                            ntree = 200)
  save(fit.rndfor, file="models/rndfor.dat")
} else {
  load("models/rndfor.dat")
}

yhat.test.rndfor <- predict(fit.rndfor, air.test_input)
rsq.rndfor <- mean((air.test_output - yhat.test.rndfor) ^ 2)

print(sprintf("Random Forest: rsq %.2f and the prediction from the mean is %.2f", rsq.rndfor, rsq.frommean))
```

## Boosted tree
```{r boosting, message=FALSE, warning=FALSE}
library(gbm)
library(survival)
library(lattice)
library(splines)
library(parallel)

fit.btree <- gbm(air_formula, data = atrain, distribution = "gaussian",
                 n.trees = 100, interaction.depth = 2, shrinkage = 0.001)
#Try different n.trees, interaction.depth, and shrinkage parameters. And, let’s compute an R2.
 
yhat.test.btree <- predict(fit.btree, atest, n.trees = gbm.perf(fit.btree, plot.it = FALSE)) 
rsq.btree <- mean((yhat.test.btree - air.test_output) ^ 2)

print(sprintf("Boosting: rsq %.2f and the prediction from the mean is %.2f", rsq.btree, rsq.frommean))
```

## Plotting the Trees of the Random Forest

```{r plot_trees, echo=FALSE, message=FALSE, warning=FALSE}
if (0) {
  library(dplyr)
  library(ggraph)
  library(igraph)
    
tree_func <- function(final_model, tree_num) {

  # get tree by index
  tree <- randomForest::getTree(final_model,
                                k = tree_num,
                                labelVar = TRUE) %>%
    tibble::rownames_to_column() %>%
    # make leaf split points to NA, so the 0s won't get plotted
    mutate(`split point` = ifelse(is.na(prediction), `split point`, NA))
  
  # prepare data frame for graph
  graph_frame <- data.frame(from = rep(tree$rowname, 2),
                            to = c(tree$`left daughter`, tree$`right daughter`))
  
  # convert to graph and delete the last node that we don't want to plot
  graph <- graph_from_data_frame(graph_frame) %>%
    delete_vertices("0")
  
  # set node labels
  V(graph)$node_label <- gsub("_", " ", as.character(tree$`split var`))
  V(graph)$leaf_label <- as.character(tree$prediction)
  V(graph)$split <- as.character(round(tree$`split point`, digits = 2))
  
  # plot
  plot <- ggraph(graph, 'dendrogram') + 
    theme_bw() +
    geom_edge_link() +
    geom_node_point() +
    geom_node_text(aes(label = node_label), na.rm = TRUE, repel = TRUE) +
    geom_node_label(aes(label = split), vjust = 2.5, na.rm = TRUE, fill = "white") +
    geom_node_label(aes(label = leaf_label, fill = leaf_label), na.rm = TRUE, 
					repel = TRUE, colour = "white", fontface = "bold", show.legend = FALSE) +
    theme(panel.grid.minor = element_blank(),
          panel.grid.major = element_blank(),
          panel.background = element_blank(),
          plot.background = element_rect(fill = "white"),
          panel.border = element_blank(),
          axis.line = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_blank(),
          axis.ticks = element_blank(),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          plot.title = element_text(size = 18))
  
  print(plot)
}

  # pick the tree with least nodes
  tree_num <- which(fit.rndfor$forest$ndbigtree == min(fit.rndfor$forest$ndbigtree))
  tree_func(final_model = fit.rndfor, tree_num)
}

```

